services:
  api:
    image: water-gas-consumption
    container_name: water-gas-consumption
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
     - "80:3000"
    volumes:
      - .:/app
    networks: 
      - water-gas-consumption
    env_file: ".env"
    environment:
      - MONGO_DB=mongodb://water-gas-consumption-db:27017/consumption
      - EXTRACT_MEASURE_PROMPT=a partir dessa imagem, retornar o valor que esta indicado
  db:
    container_name: water-gas-consumption-db
    ports:
     - "27017:27017"
    image: mongo
    volumes:
     - water-gas-consumption:/data/db
    networks: 
     - water-gas-consumption

volumes:
 water-gas-consumption:

networks:
 water-gas-consumption:

