name: water-gas-consumption

services:
  api:
    image: water-gas-consumption
    container_name: water-gas-consumption
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
     - "80:3000"
    volumes:
      - .:/app/dev
    networks: 
      - water-gas-consumption
    env_file: ".env"
    environment:
      - MONGO_DB=mongodb://water-gas-consumption-db:27017/consumption
      - EXTRACT_MEASURE_PROMPT=a partir dessa imagem, retornar o valor que esta indicado
      - MINIO_ROOT_PASSWORD=minioadmin   
      - TZ=America/Sao_Paulo
  db:
    container_name: water-gas-consumption-db
    ports:
     - "27017:27017"
    image: mongo
    volumes:
     - mongo-db:/data/db
    networks: 
     - water-gas-consumption
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  
      - "9001:9001"  
    environment:
      - MINIO_ROOT_USER=minioadmin       
      - MINIO_ROOT_PASSWORD=minioadmin   
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
    networks: 
     - water-gas-consumption

volumes:
 mongo-db:
 minio:

networks:
 water-gas-consumption:

